services:
  - type: web
    name: pjsofonic-erp-backend
    env: node
    region: singapore
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://mr_coder_04:ak29SiBp5TG-gy1DBpPYcg@pjsofonicerp-31535.j77.aws-ap-south-1.cockroachlabs.cloud:26257/PJsofonic_erp?sslmode=verify-full
      - key: EMS_BACKEND_URL
        value: https://erp-backend-1-02lc.onrender.com/api
      - key: CRM_BACKEND_URL
        value: https://pjsofonic-crm-backend.onrender.com
